### PR TITLE
leigthweight -> lightweight

### PR DESCRIPTION
**Pull request by therumbler**

### CODE REVIEW

**Comment by gregordr** [comment]
Thanks!

**Comment by gregordr** [comment]
However, in the code you changed it to `ligthweight`, instead of `lightweight`. Could you fix that?

**Comment by therumbler** [comment]
> However, in the code you changed it to `ligthweight`, instead of `lightweight`. Could you fix that?

🤦‍♂️ 

Fixed. very embarrassing! trying to fix a typo, with ANOTHER TYPO!! omg! haha

**Comment by gregordr** [comment]
Thanks :)

**Pull request merged**
