### PR TITLE
Addressing your previous concerns

### PR DESCRIPTION
**Pull request by roaldi**
I don't mess around with node very much, so I couldn't tell you how to secure the frontend through that avenue. What I can do is add an interactive portion at the end of the script to give the user the option to enable the firewall (since ufw/iptables are off by default on fresh installs). When that happens, they would be queried for any ports they need to stay open, and by default block everything except for 8080 and the user noted ports. 

For security, I plan on adding a random password from /dev/random for the postgres "imagestore" user. This would prevent anyone using that user from gaining access via default passwords. Users would still be able to control the database, and change the password of "imagestore" via the user "postgres".

For nginx configs, I can change things around so that it just adds a site if it sees others are there, so it doesn't stomp on anything.

As for secure deployment, It should be just cd into dir, run script. Doing my best to take the user out of the equation as much as possible.

### CODE REVIEW

**Comment by gregordr** [comment]
I think for the frontend, `npx serve -s build -l tcp://localhost:3000` will be fine. (Obviously we also need a building step before that).

For the backend however, I will investigate a bit more and report back when I have a working solution. I don't think adding a firewall is necessary, as we shouldn't expose any ports publicly anyway.

The database solution sounds good! 

Nginx also sounds good.

The deployment procedure sounds simple enough, it would be great if you could write those two steps into the readme file though!

**Comment by roaldi** [comment]
Will do. I will try out npx as a solution, and implement the database and nginx solutions.

**Comment by roaldi** [comment]
As a side note, I don't want to distract you from building the core app. I'll focus on making it work outside of docker, as long as you can assist me with node stuff every now and then.

**Comment by gregordr** [comment]
Sure thing! Thanks for taking care of this :)

**Comment by roaldi** [comment]
I tried implementing serving the frontend with npx, and something broke down between nginx and the react app. Database solution and nginx solution worked as intended. Script does a socket search, greps for 8080, and if it finds it, asks the user for another port number, doing some basic input validation with regex.

**Comment by gregordr** [comment]
> something broke down between nginx and the react app

That's really odd :/ I will look into it when I have a while

Good to hear the rest is working though!

**Comment by roaldi** [comment]
What do you mean by build? Only thing I did different is instead of invoking npm start with the front end service, I did the npx command

**Comment by gregordr** [comment]
Ah I see! So the serve build... command serves a folder called build. That folder is created by calling `npm run-script build` in the folder with the frontend source files, in which you also run `npm i` first. That may be the issue you ran into!

**Comment by roaldi** [comment]
Take a look now. Would the npx serving also work for the backend?

**Comment by gregordr** [comment]
Looks good! It won't work for the backend, as serve just makes a folder and its contents accessible. The backend has logic that needs to run. However, I think I have a fix in the next few days.

**Comment by roaldi** [comment]
Sounds good. If its anything like the frontend, it'll be just as easy to implement.

**Comment by roaldi** [comment]
Will write up instructions and info. As for the question of a preexisting DB, there won't be any issue unless they already have a role "imagestore" and a database "imagestore".

**Comment by gregordr** [comment]
I believe 6022627782ecd2436b69f74bcab2f46f113cbe2a should fix the issues, and backend should only be accessible from localhost by default. I will just test if the containers still work.

**Comment by gregordr** [comment]
Alright, can confirm it works! I will merge as soon as you add instructions.

**Comment by roaldi** [comment]
Instructions added along with some additional information. Let me know if it needs added to/needs to be changed.

**Comment by gregordr** [comment]
Can you add the commands for stopping/starting again too?

**Comment by roaldi** [comment]
Done.

**Comment by gregordr** [comment]
Perfect, thanks!

**Pull request merged**
